# Generated by Django 3.0.4 on 2020-05-04 09:23

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evacompany_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=55, verbose_name='Adı')),
                ('worker_sirname', models.CharField(max_length=55, verbose_name='Familiya')),
                ('worker_fin', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='Fin')),
                ('is_bm', models.BooleanField(default=False)),
                ('is_as', models.BooleanField(default=False)),
                ('worker_created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='evaluate.EvaluationCompany', verbose_name='Qiymətləndirici təşkilat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Sifarişin adı')),
                ('order_law_decision', models.CharField(max_length=255, verbose_name='Rayon məhkəməsinin qərarı')),
                ('order_deptor', models.CharField(max_length=255, verbose_name='Borclu')),
                ('order_claimant', models.CharField(max_length=255, verbose_name='Tələbkar')),
                ('order_information', ckeditor.fields.RichTextField(verbose_name='Əmlak haqqında məlumat')),
                ('order_document', models.FileField(upload_to='order_documents/%Y/', verbose_name='Əmlakın texniki sənədlərini daxil edin')),
                ('order_keep_date_location', models.CharField(max_length=255, verbose_name='Saxlanma yeri və tarix')),
                ('order_mobile', models.CharField(max_length=13, verbose_name='Sifarişçinin mobil nömrəsi')),
                ('is_done', models.BooleanField(default=False)),
                ('order_created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ManyToManyField(related_name='orders', to='evaluate.EvaluationCompany', verbose_name='Qiymətləndirici təşkilat')),
            ],
        ),
    ]
