# Generated by Django 3.0.6 on 2020-05-29 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0004_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationorder',
            name='subcategory_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories_evaluationorder', to='evaluate.SubCategory', verbose_name='Kateqoriya'),
            preserve_default=False,
        ),
    ]
