# Generated by Django 3.0.4 on 2020-05-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0006_apartment_enterprisecomplex_landplot_nonresidentialarea_nonresidentialbuilding_otherrealstate_privat'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprisecomplex',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landplot',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonresidentialarea',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonresidentialbuilding',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherrealstate',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatehouse',
            name='price',
            field=models.FloatField(default=0, verbose_name='Qiymət'),
            preserve_default=False,
        ),
    ]
