# Generated by Django 3.0.4 on 2020-04-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fin', models.CharField(max_length=7, unique=True)),
                ('username', models.CharField(max_length=55)),
                ('sirname', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avtive', models.BooleanField(default=True)),
                ('company_user', models.BooleanField(default=False)),
                ('customer_user', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
