# Generated by Django 3.0.4 on 2020-04-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avtive',
            new_name='active',
        ),
    ]
