# Generated by Django 3.0.4 on 2020-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200409_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_mahkama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='icra_company',
            field=models.BooleanField(default=False),
        ),
    ]
