# Generated by Django 3.0.4 on 2020-04-09 15:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_boss', models.CharField(max_length=255)),
                ('company_specialist', models.CharField(max_length=255)),
                ('company_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255, verbose_name='Sifarişin adı')),
                ('order_law_decision', models.CharField(max_length=255, verbose_name='Rayon məhkəməsinin qərarı')),
                ('order_deptor', models.CharField(max_length=255, verbose_name='Borclu')),
                ('order_claimant', models.CharField(max_length=255, verbose_name='Tələbkar')),
                ('order_information', ckeditor.fields.RichTextField()),
                ('order_document', models.FileField(upload_to='', verbose_name='Əmlakın texniki sənədlərini daxil edin')),
                ('order_keep_date_location', models.CharField(max_length=255, verbose_name='Saxlanma yeri və tarix')),
                ('order_mobile', models.CharField(max_length=13, verbose_name='Sifarişçinin mobil nömrəsi')),
                ('order_created_date', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.CustomerCompany', verbose_name='Sifarişçi təşkilat')),
            ],
            options={
                'ordering': ['-order_created_date'],
            },
        ),
    ]
