# Generated by Django 3.0.4 on 2020-04-09 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_information',
            field=ckeditor.fields.RichTextField(verbose_name='Əmlak haqqında məlumat'),
        ),
    ]
