# Generated by Django 3.0.4 on 2020-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200409_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_document',
            field=models.FileField(upload_to='order_documents/%Y/', verbose_name='Əmlakın texniki sənədlərini daxil edin'),
        ),
    ]
