# Generated by Django 3.0.6 on 2020-05-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0006_apartment_enterprisecomplex_landplot_nonresidentialarea_nonresidentialbuilding_otherrealstate_privat'),
        ('orders', '0004_auto_20200412_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subcategory_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcategories', to='evaluate.SubCategory', verbose_name='Kateqoriya'),
            preserve_default=False,
        ),
    ]
