# Generated by Django 3.0.4 on 2020-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_subcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_one',
            field=models.FloatField(default=0, verbose_name='Qiymət 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_three',
            field=models.FloatField(default=0, verbose_name='Qiymət 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price_two',
            field=models.FloatField(default=0, verbose_name='Qiymət 2'),
            preserve_default=False,
        ),
    ]
