# Generated by Django 3.0.4 on 2020-05-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200531_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price_one',
            field=models.FloatField(null=True, verbose_name='Qiymət 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_three',
            field=models.FloatField(null=True, verbose_name='Qiymət 3'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_two',
            field=models.FloatField(null=True, verbose_name='Qiymət 2'),
        ),
    ]
