# Generated by Django 3.0.4 on 2020-06-01 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0007_auto_20200531_1101'),
        ('orders', '0007_auto_20200531_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eva_company_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evacompanyone', to='evaluate.EvaluationCompany', verbose_name='Qiymətləndirici təşkilat 1'),
        ),
        migrations.AddField(
            model_name='order',
            name='eva_company_three',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evacompanythree', to='evaluate.EvaluationCompany', verbose_name='Qiymətləndirici təşkilat 3'),
        ),
        migrations.AddField(
            model_name='order',
            name='eva_company_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evacompanytwo', to='evaluate.EvaluationCompany', verbose_name='Qiymətləndirici təşkilat 2'),
        ),
    ]
