# Generated by Django 3.0.4 on 2020-06-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200601_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='choosen_price',
            field=models.FloatField(null=True, verbose_name='Seçilmiş qiymət'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_choosed',
            field=models.BooleanField(default=False),
        ),
    ]
